### ISSUE TITLE
[TODO] Core: improve performance

### ISSUE THREAD

**Issue by wangwenx190** [wangwenx190/framelesshelper#248]
Things we can improve (not complete):

- [ ] We are copying most XXXData structs when we want to have a readonly copy. We should use const reference instead.
- [ ] For Qt contains (QHash, QMap, QList, etc), we are using `contains` first and then get some value, this involves two times of lookup operation. We should use `std::find_if` or something like that to avoid double lookups.
- [ ] Change QByteArray to const char * to be able to use constexpr.
